version: 1.0.{build}
image: Visual Studio 2019
configuration: Release
platform: x64
environment:
  OpenSSL_Home: C:\OpenSSL-v332-Win64\
install:
- git submodule init
- git submodule update
build:
  project: Ssl-Example.sln
  verbosity: minimal
