version: 1.0.{build}
image: Visual Studio 2019
configuration: Release
platform: x64
environment:
  OpenSSL_Home: C:\OpenSSL-v33-Win64\
install:
- git submodule init
- git submodule update
- cmd: copy /Y C:\OpenSSL-v33-Win64\lib\ C:\OpenSSL-v33-Win64\
build:
  project: Ssl-Example.sln
  verbosity: minimal
